version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./merchandise.db:/app/merchandise.db
    environment:
      - SECRET_KEY=change-this-in-production
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - web
    restart: always 